services:

  mysql:
    image: mysql:8.4
    container_name: mysql-pfe
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pfe
      MYSQL_USER: pfe
      MYSQL_PASSWORD: pfe
    ports:
      - "3306:3306"
    volumes:
      - pfe_mysql_data:/var/lib/mysql

  backend:
    build: ./pfeFinalBack-master
    container_name: pfe-backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  frontend:
    build:
      context: ./pfeFinal-master
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  pfe_mysql_data: