apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: backend-allow-frontend
spec:
  podSelector:
    matchLabels:
      app: pfe-backend
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: pfe-frontend
    ports:
    - protocol: TCP
      port: 8080
  policyTypes:
  - Ingress