name: CI DevSecOps Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  backend:
  runs-on: ubuntu-latest

  services:
    sonarqube:
      image: sonarqube:latest
      ports:
        - 9000:9000

  steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Wait for SonarQube to start
      run: sleep 60

    - name: Build and Run Tests
      run: mvn clean verify
      working-directory: ./pfeFinalBack-master

    - name: SonarQube Analysis
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=pfe-backend \
        -Dsonar.host.url=http://localhost:9000 \
        -Dsonar.login=admin \
        -Dsonar.password=admin
      working-directory: ./pfeFinalBack-master

    - name: OWASP Dependency Check
      run: mvn org.owasp:dependency-check-maven:check
      working-directory: ./pfeFinalBack-master

    - name: Build Docker Image Backend
      run: docker build -t username/pfe-backend:latest .
      working-directory: ./pfeFinalBack-master


  frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: ./pfeFinal-master/package-lock.json

      # ðŸ”¹ Install Dependencies
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./pfeFinal-master

      # ðŸ”¹ Run Frontend Tests
      - name: Run Frontend Tests
        run: npm run test -- --watch=false --browsers=ChromeHeadless
        working-directory: ./pfeFinal-master

      # ðŸ”¹ Build Frontend
      - name: Build Frontend
        run: npm run build
        working-directory: ./pfeFinal-master

      # ðŸ”¹ Build Docker Image Frontend
      - name: Build Docker Image Frontend
        run: docker build -t username/pfe-frontend:latest .
        working-directory: ./pfeFinal-master